name: "Deploy dev server"

on:
  push:
    branches:
      - "master"
      - "feature/ci-cd-**"

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Run checks"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    needs:
      - check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build
        env:
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_REDIRECT_URL: ${{ env.OAUTH_GITHUB_REDIRECT_URL }}
          NITRO_PRESET: ${{ env.NITRO_PRESET }}
          API_ORIGIN: ${{ env.API_ORIGIN }}
          OAUTH_GITHUB_REDIRECT_URL: ${{ env.OAUTH_GITHUB_REDIRECT_URL }}
          WORKSPACE_ORIGIN: ${{ env.WORKSPACE_ORIGIN }}

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir .netlify/functions-internal \
            --site ${{ secrets.DEV_SITE_ID }} \
            --auth ${{ secrets.DEV_AUTH_TOKEN }}

      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=/ --functions=/
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.DEV_SITE_ID }}
