name: "Deploy dev server"

on:
  push:
    branches:
      - "master"
      - "feature/ci-cd-**"

jobs:
#  check:
#    runs-on: ubuntu-latest
#    name: "Run checks"
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#
#      - run: npm install
#      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
#    needs:
#      - check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build
        env:
          NITRO_PRESET: netlify_builder
          API_ORIGIN: https://lamion-api.onrender.com
          AUTH_ORIGIN: https://lamion-api.onrender.com
          WORKSPACE_ORIGIN: https://lamionapp.netlify.app/
          GITHUB_CLIENT_ID: Ov23lih2nox7FoE15le0
          GITHUB_REDIRECT_URL: https://lamionapp.netlify.app/auth/oauth/github

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_SITE_ID }}
        with:
          args: deploy
          production-deploy: true
