name: "Deploy dev server"

on:
  push:
    branches:
      - "master"
      - "feature/ci-cd-**"

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_SITE_ID }}
        with:
          args: deploy
